version: "3"

services:
 node:
   build: .
   volumes:
     - ./views:/usr/src/app/views
     - ./static:/usr/src/app/static
     - ./config:/usr/src/app/config
   environment:
     - KEY=VALUE
   links:
     - mongo
   depends_on:
     - mongo
   ports:
     - "8080:80"
   tty: true
   stdin_open: true

 mongo:
   image: mongo:4.4.9
   ports:
     - "27017:27017"
   volumes:
     - ./mongo:/data/db
